name: poly
description: A library for checking if given point(s) is present inside Polygon or not.
version: 1.0.7+2
homepage: https://github.com/Sacchid/poly
author: sacchi <22224760+Sacchid@users.noreply.github.com>

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  csv: ^5.0.1
  collection: ^1.16.0
#  spreadsheet_decoder: ^1.0.1
#  json_serializable: ^2.1.0y
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.4
#  test_coverage: ^0.2.0
